### ISSUE TITLE
Lux terminates before completing all commands

### ISSUE THREAD

**Issue by mvxt** [hawk/lux#16]
Hello, I have the following script I am running:

```
13[shell func-027]
14  [progress 'Function-27 Start']
15
16  # Create service order, check dry-run output, commit
17  [progress 'Dry-Run']
18  [invoke func027_033_068_074_rest $DEVICE0 $TENGIGE $FUNC027 $DRY_RUN ${LOGDRY}-CREATE.tmp]
19  !bash compare.sh ../expected/native/FUNC-027 ${LOGDRY}-CREATE.tmp
20  ?Partial True
21  [progress 'Commit']
22  [invoke func027_033_068_074_rest $DEVICE0 $TENGIGE $FUNC027 $COMMIT ${LOGCOMMIT}-CREATE.tmp]
23  !grep '201 Created' ${LOGCOMMIT}-CREATE.tmp
24  ?HTTP/1.1 201 Created
25
26  # Delete the service order
27  [progress 'FUNC-027 Delete']
28  [invoke delete_service_order_dryrun_rest $COMMIT $SERVICE $FUNC027 ${LOGDRY}-DELETE.tmp]
29  !if grep --quiet "error" ${LOGDRY}-DELETE.tmp; then echo 'Dry-run failed. Exiting'; exit 1; fi
30  [invoke delete_service_order_rest $COMMIT $SERVICE $FUNC027 ${LOGCOMMIT}-DELETE.tmp]
31  !if grep --quiet "error" ${LOGCOMMIT}-DELETE.tmp; then echo 'Dry-run failed. Exiting'; exit 1; fi
32  #?bubba
33
34[cleanup]
35  [progress 'Cleanup']
36  [invoke delete_service_order_rest $COMMIT $SERVICE $FUNC027 ${LOGCOMMIT}-CLEANUP.tmp]
```

Lines 28 and 30 call macros which essentially just run a cURL command and redirect the output into a file. However, these macros consistently do not finish executing because Lux exits immediately after successfully sending the command. One of the macros is attached below.

```
313##
314# Delete a service order, dryrun, through REST API/cURL command, pipe into file
315#  @param SERVICE - Service name
316#  @param ORDER - Order name
317#
318[macro delete_service_order_rest url service order file]
319    !curl -is -X DELETE -u admin:admin $url/$service/$order >> $file
320[endmacro]
```

I have come to this conclusion by artificially adding an expects line and letting the script time out and fail (see line 32 above, currently commented out). When the script times out, all of the expected files are printed to properly, but when the expect line is commented out, the script finishes very quickly and the shell terminates before all output is piped to the files.

Is there a way around this? I already tried `sleep 5` but that didn't work, script still finished instantly. Thanks for your time!

**Comment by ksallberg** [comment]
Probably you should expect something after your curl command, (or after the bash commands later). For instance the exit code of it. So that lux waits until completion of the commands before moving on.

Something like:

`[macro delete_service_order_rest url service order file]
    !curl -is -X DELETE -u admin:admin $url/$service/$order >> $file
    !echo ==$?==
    ?==0==
[endmacro]`

**Comment by hawk** [comment]
That's the way of doing it. Or you can simply wait for the shell prompt, if you don't care about the result of the command. Or do a combination to be on the safe side.

Be a little careful though about issuing multiple commands in rapid order. "curl" is probably ok, but there are other commands such as "ant" that reads from stdin. If "curl" was such a (stdin reading) command the string "echo ==$?=="  (in Christians example above) could sometimes be consumed by the command reading from stdin and sometimes be executed by the shell, depending on timing.

If you would like to cope with such a race condition you would need to first match on something indicating that the command has finished (such as the shell prompt) before you issue the next command (in this case echo).

> [macro delete_service_order_rest url service order file]
>    !curl -is -X DELETE -u admin:admin $url/$service/$order >> $file
>    ?SH-PROMPT:
>    !echo ==$?==
>    ?==0==
>[endmacro]

or ensure that the command does not read from stdin:

> !ant < /dev/null
> !echo ==$?==
> ?==0==

It is however good practice to match on something (like the shell prompt) before going ahead with the execution. It usually makes the outcome of test scripts more predictable.

**Comment by mvxt** [comment]
Hello hawk & ksallberg,

Thanks for your prompt responses! I gave your suggestions a try and it has solved my problem.

Though, I should add that hawk's first suggestion ("simply wait for the shell prompt") **_didn't do the trick_** - I had to echo/expect the exit code to get it to work. I'm actually somewhat curious as to why that would be, as you'd expect the shell prompt not to return until the command has finished. I'll have to poke around a little more and see what's going on.

**Comment by hawk** [comment]
Check the lux event log to see in what order things happened. More specifically which shell prompt that matched. It may be the case that there already was an unmatched shell prompt in the output stream when the "curl" command was issued. Then you may have matched a prompt from a previous command.
