### ISSUE TITLE
Running Lux script on mac throws warning - Missing summary doc

### ISSUE THREAD

**Issue by gmathew18** [hawk/lux#23]
Getting the following warning, 

result            : WARNING
successful        : 0
warnings          : 1
************.lux:0 - Missing summary doc
summary           : WARNING

Is there a way to fix this, or supress it so that my test can provide success result

**Comment by ksallberg** [comment]
Yes, provide a doc line to the top of your test, like such:
[doc Some doc]

**Comment by gmathew18** [comment]
Thanks. that fixed it
