### ISSUE TITLE
Setting priority on Lux documents.

### ISSUE THREAD

**Issue by jemagu** [hawk/lux#29]
We often start our Lux test like this `$ lux *.lux`, one problem with this is that sometimes certain lux files need to be executed before others. We solve this with a naming standard but it´s a bit cumbersome. Would it be possible to add priority to a Lux document?

```lux
[doc Run this test first]
[priority 1]
...
```
```lux
[doc Basic test]
[priority 2]
...
```
```lux
[doc Standard test]
[priority 2]
...
```

**Comment by hawk** [comment]
I am a bit hesitant of introducing a feature like this as it encourages
people to introduce test cases that are dependant of each other. In most
cases I think this is a bad idea. What problem do you want to solve by
running the test cases in a specific order?

/Håkan

**Comment by jemagu** [comment]
In hindsight I agree with you, I would probably solve one problem but introduce another. Our tests configures Cisco NSO, setting up a pretty large structure with some dependencys in multiple layers making it tricky to isolate tests. But this is not the way to solve it.
