### ISSUE TITLE
incorrect match behaviour after loop

### ISSUE THREAD

**Issue by mbj4668** [hawk/lux#34]
I have the following lux script:

```
[shell topdc]
    # <stuff>
    [loop wait 1..30]
        # set a loop break pattern
        @oper-status: scheduled
        !$supctl -d .topdc show state application-deployments health-infra
        ?SH-PROMPT
        [sleep 1]
    [endloop]
    """?
      applications:
        - name: health
          datacenters:
            - udc1
    SH-PROMPT:
    """
```

This sometimes fails (most of the time it works!) with:

```
    applications:
      - name: health
        datacenters:
          - udc1
- SH-PROMPT:
+ SH-PROMPT
```

I.e., lux thinks that it doesn't get the last ":".  But the ":" is there in the stdout log from the "topdc" shell.

Here's some more interesting logs:

```
00:09:59.150605 topdc(184): recv "name: health-infra\napplications:\n  - name: health\n    placement:\n      match-dc-labels: |\n        dm-env/type = edge and dm-env/name = udc1\nstatus:\n  oper-status: scheduled\n  applications:\n    - name: health\n      datacenters:\n        - udc1\nSH-PROMPT:"
00:09:59.150720 topdc(184): timer canceled (after 112286 micro seconds)
00:09:59.150842 topdc(184): skip ":../../../../../bin/supctl -d .topdc show state application-deployments health-infra\nname: health-infra\napplications:\n  - name: health\n    placement:\n      match-dc-labels: |\n        dm-env/type = edge and dm-env/name = udc1\nstatus:\n  "
00:09:59.150916 topdc(184): match loop break pattern matched "oper-status: scheduled"
00:09:59.151856 topdc(193): expected* "  applications:\\R    - name: health\\R      datacenters:\\R        - udc1\\RSH-PROMPT:"
00:09:59.151903 topdc(193): timer started (10 seconds * 2.000 multiplier)
```

So here lux has successfully matched the loop break pattern, and is now waiting for the next pattern.  Note that it has received the expected output already at 00:09:59.150605.

Next, in the log we have:

```
00:10:19.152328 topdc(193): recv "match_timeout"
00:10:19.152799 topdc(193): timer failed (after 20000840 micro seconds)
00:10:19.152984 topdc(193): skip "\n  applications:\n    - name: health\n      datacenters:\n        - udc1\nSH-PROMPT"
00:10:19.153090 topdc(193): stop fail
00:10:19.153177 topdc(193): where "193"
00:10:19.153225 topdc(193): stack "run.lux:193" expect 
00:10:19.153268 topdc(193): inactivate after delete
```

And in the stdout text log we have:

```
SH-PROMPT:../../../../../bin/supctl -d .topdc show state application-deployments health-infra
name: health-infra
applications:
  - name: health
    placement:
      match-dc-labels: |
        dm-env/type = edge and dm-env/name = udc1
status:
  oper-status: scheduled
  applications:
    - name: health
      datacenters:
        - udc1
SH-PROMPT:
```

**Comment by SimonUnge** [comment]
I've struggled a bit with loops, but found that this pattern works:
```
[macro wait-for command match max_time prompt]
    [loop i 1..$max_time]
        @$match
        !$command
        ??$command
        ?$prompt
        [sleep 1]
    [endloop]
    # The last prompt won't match since the loop pattern will                                                                                                                                                        
    # match before it, so match it here instead.                                                                                                                                                                     
    ?$prompt

    # Sync up after the loop.                                                                                                                                                                                        
    !$command
    ??$command
    ?$prompt
[endmacro]
```

**Comment by mbj4668** [comment]
I did something similar as a workaround, but I think it would be good to fix this bug (assuming it is a bug).

**Comment by hawk** [comment]
Is it possible to reproduce the problem with lux-2.4.1?

**Comment by mbj4668** [comment]
With 2.3.2 the problem only happened "sometimes" and only on some machines.  I have updated to 2.4.1 and so far the problem hasn't happened.  We can close this issue for now, and then I can re-open if the problem happens again.

Thanks!

**Comment by hawk** [comment]
Great. Please, keep in touch if it happens again.

**Comment by mbj4668** [comment]
Ok, it happened again, on 2.4.1.

**Comment by mbj4668** [comment]
Here's a simple test to reproduce this:

tst.txt:
```
oper-status: scheduled
  applications:
    - name: health
      datacenters:
        - udc1
```

bug.lux:
```
[shell test]
    [loop wait 1..30]
        # set a loop break pattern
        @oper-status: scheduled
        !cat tst.txt
        ?SH-PROMPT
        [sleep 1]
    [endloop]
    """?
      applications:
        - name: health
          datacenters:
            - udc1
    SH-PROMPT:
    """
```

run this in a loop until it fails.

**Comment by SimonUnge** [comment]
I do think its needed, regardless of bug, to match the prompt again directly after the loop though?

**Comment by mbj4668** [comment]
No, when the break pattern matches, "the rest" is left unmatched.  After the loop, I match on the rest + prompt.

**Comment by SimonUnge** [comment]
Ah, yes ok ofc.

**Comment by hawk** [comment]
Thanks for re reproduction case.

**Comment by hawk** [comment]
Interesting bug. The command "cat tst.txt" prints out the contents of a file. When it is done a shell prompt is printed. Most times Lux receives those characters from the port program as a chunk without the trailing prompt. Now and then the prompt is printed fast enough and is included in the same chunk. It was those rare cases that triggered the bug. On my machine it happened quite random. Sometimes it required more than 4000 runs. Sometimes as few as 5. In order to trigger the bug, the chunk both needed to match the loop break pattern and the prompt. In your test case the regexp was written to only match "SH-PROMPT" and not "SH-PROMPT:". That little typo was also needed to trigger the bug.

Anyway, I think that I have fixed the bug now. But I need to run regression tests before I want to release it. For the time being the fix resides on the "develop" branch.

**Comment by hawk** [comment]
Running the reproduction case caused the error 19 times out of 102262. Suppose that would qualify as intermittent failure.

**Comment by mbj4668** [comment]
:)  Probably dependent on the environment.  On my machine it happens perhaps 1 out of 5 times.

**Comment by hawk** [comment]
I have now released Lux 2.4.2 containing a fix for the problem. It caused some regression issues, but so far as I could see those were triggered by test cases which depended on the old broken behavior.

It is quite easy to compare an old bad run with a new good run by searching for "loop break pattern matched” in the respective event log. The subsequent entry in the log is called “rest” and contains the remains in the stdout buffer after the break pattern has matched. In the old runs Lux sometimes truncated the stdout buffer in that situation. Output from the port program was lost. It did however not occur everytime. It depended on timing and how the test case was written.

**Comment by hawk** [comment]
The "rest" entry in the event log was introduced in commit #0b38952. You can use that (old) version of the system if you want to compare details of an old bad run with a new good one using Lux 2.4.2.

**Comment by mbj4668** [comment]
Thanks for fixing this problem!
