### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by danablair** [hawk/lux#4]
I just cloned lux and there is an error in make

make
"/usr/local/bin/erlc" +warnings_as_errors +warn_unused_vars +debug_info -o ../ebin lux.erl
"/usr/local/bin/erlc" +warnings_as_errors +warn_unused_vars +debug_info -o ../ebin lux_debug.erl
"/usr/local/bin/erlc" +warnings_as_errors +warn_unused_vars +debug_info -o ../ebin lux_html.erl
compile: warnings being treated as errors
lux_html.erl:761: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
make[1]: *** [../ebin/lux_html.beam] Error 1
gcc -o ../priv/bin/runpty -g -O2 -Wall  runpty.c
DBLAIR-M-2027:lux danablair$ pwd
/Users/danablair/lux

**Comment by hawk** [comment]
I will fix it. A workaround is to either remove the +warnings_as_errors
compiler flag or to use an older release of Erlang/OTP.

/Håkan

**Comment by hawk** [comment]
Now it is fixed.

Make a "git pull" and re-make lux.

Please keep in touch if you encounter problems.

/Håkan

**Comment by danablair** [comment]
thx.downloaded, built and run successfully
