### ISSUE TITLE
brew install lux , not ok

### ISSUE THREAD

**Issue by etnt** [hawk/lux#55]
Hi,

On Mac, `brew install lux` , seem to install something completely different.

Mors, Tobbe ;-)

**Comment by hawk** [comment]
You need to do:

brew tap hawk/homebrew-hawk

brew install hawk/hawk/lux

BTW, now brew will install Lux 3.0 and not an old 2.x.

/Håkan

**Comment by etnt** [comment]
Aha, great thanks!
